'use client';
import { useEffect, useRef, useState } from 'react';

export default function CashierAdvancesPage() {
  const [employees,setEmployees]=useState([]); const [policy,setPolicy]=useState(null); const [form,setForm]=useState({staffId:'',amount:'',paymentMethod:'cash',note:''}); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const key=useRef(null);
  const headers=()=>({Authorization:`Bearer ${localStorage.getItem('pos_token')}`});
  const load=async()=>{const response=await fetch('/api/payroll/advances',{headers:headers()});const data=await response.json();if(response.ok){setEmployees(data.employees||[]);setPolicy(data.policy);}else setMessage(data.error||'Unable to load advances');};
  useEffect(()=>{load();},[]);
  const submit=async(event)=>{event.preventDefault();setBusy(true);setMessage('');if(!key.current)key.current=crypto.randomUUID();const response=await fetch('/api/payroll/advances',{method:'POST',headers:{...headers(),'Content-Type':'application/json','Idempotency-Key':key.current},body:JSON.stringify({...form,staffId:Number(form.staffId),amount:Number(form.amount)})});const data=await response.json();setBusy(false);if(!response.ok){setMessage(data.error||'Unable to issue advance');return;}key.current=null;setForm({staffId:'',amount:'',paymentMethod:'cash',note:''});setMessage('Salary advance issued and recorded in the drawer/account.');load();};
  const selected=employees.find(employee=>String(employee.id)===String(form.staffId));
  return <main className="min-h-screen bg-gray-50 p-4 sm:p-8"><div className="mx-auto max-w-3xl"><h1 className="text-2xl font-semibold text-gray-950">Issue salary advance</h1><p className="mt-1 text-sm text-gray-600">Cashiers can issue advances only. Full salary payments, edits, reversals, and deletions remain Admin-only.</p>{message?<div className="my-4 rounded-lg border bg-white p-3 text-sm">{message}</div>:null}{policy&&!policy.configured?<div className="my-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Advances are locked until Admin configures the ceiling in Settings.</div>:null}<form onSubmit={submit} className="mt-5 space-y-4 rounded-xl border bg-white p-5"><label className="block text-sm font-medium">Employee<select required value={form.staffId} onChange={e=>setForm({...form,staffId:e.target.value})} className="mt-1 w-full rounded-lg border p-3"><option value="">Select employee</option>{employees.map(employee=><option key={employee.id} value={employee.id}>{employee.name} · {employee.role}</option>)}</select></label>{selected?<div className="grid grid-cols-3 gap-2 text-sm"><div className="rounded-lg bg-gray-50 p-3"><span className="block text-xs text-gray-500">Outstanding</span>Rs {selected.outstandingAdvance.toFixed(2)}</div><div className="rounded-lg bg-gray-50 p-3"><span className="block text-xs text-gray-500">Issued this period</span>Rs {selected.periodIssued.toFixed(2)}</div><div className="rounded-lg bg-gray-50 p-3"><span className="block text-xs text-gray-500">Remaining allowed</span>Rs {selected.remainingEligible.toFixed(2)}</div></div>:null}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Amount<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className="mt-1 w-full rounded-lg border p-3"/></label><label className="text-sm font-medium">Payment account<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})} className="mt-1 w-full rounded-lg border p-3"><option value="cash">Cash drawer</option><option value="online">Online / bank</option></select></label></div><label className="block text-sm font-medium">Reason / note<textarea required value={form.note} onChange={e=>setForm({...form,note:e.target.value})} className="mt-1 w-full rounded-lg border p-3" rows={3}/></label><button disabled={busy||!policy?.configured} className="rounded-lg bg-gray-950 px-5 py-3 font-semibold text-white disabled:opacity-50">{busy?'Issuing…':'Issue advance'}</button></form></div></main>;
}
