import { chromium } from 'playwright';
const BASE = 'http://localhost:3005';
const login = await fetch(`${BASE}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'qa_admin', password: 'QaPass!2026', deviceId: 'pay' }) }).then((r) => r.json());
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
await context.addInitScript(({ token, user }) => { localStorage.setItem('pos_token', token); localStorage.setItem('pos_user', JSON.stringify(user)); }, { token: login.token, user: login.user });
const page = await context.newPage();
const errors = []; page.on('pageerror', (e) => errors.push(e.message));
await page.goto(`${BASE}/admin/customer-ledger`, { waitUntil: 'networkidle', timeout: 90000 });
await page.waitForTimeout(2000);
const before = await page.locator('main section').first().innerText();
await page.locator('main ul li button').first().click();
await page.getByText('Total still owed').waitFor({ timeout: 60000 });
// open bill popup
await page.locator('[role="dialog"] ul li button').first().click();
await page.waitForTimeout(2500);
await page.screenshot({ path: 'test-results/pay-billpopup.png' });
await page.getByRole('button', { name: 'Pay this bill' }).click();
await page.waitForTimeout(800);
await page.screenshot({ path: 'test-results/pay-popup.png' });
const amount = await page.locator('input[type="number"]').first().inputValue();
await page.getByRole('button', { name: 'Post payment' }).click();
await page.waitForTimeout(3000);
const notice = await page.getByText('Payment recorded').count();
console.log('prefilled amount', amount, '| payment notice', notice);
await page.keyboard.press('Escape');
await page.waitForTimeout(2000);
console.log('banner before:', before.split('\n').slice(-1)[0], '| after:', (await page.locator('main section').first().innerText()).split('\n').slice(-1)[0]);
// print menu
await page.locator('main ul li button').first().click();
await page.getByText('Total still owed').waitFor({ timeout: 60000 });
await page.getByRole('button', { name: /Print statement/ }).click();
await page.waitForTimeout(500);
await page.screenshot({ path: 'test-results/pay-printmenu.png' });
console.log('errors', errors);
await browser.close();
