import { chromium } from 'playwright';
const BASE = 'http://localhost:3005';
const login = await fetch(`${BASE}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'qa_cashier', password: 'QaPass!2026', deviceId: 'pos' }) }).then((r) => r.json());
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 950 } });
await context.addInitScript(({ token, user }) => { localStorage.setItem('pos_token', token); localStorage.setItem('pos_user', JSON.stringify(user)); localStorage.removeItem('salon_pos_bill_draft'); }, { token: login.token, user: login.user });
const page = await context.newPage();
const errors = []; page.on('pageerror', (e) => errors.push(e.message));
await page.goto(`${BASE}/admin/billing`, { waitUntil: 'networkidle', timeout: 90000 });
await page.waitForTimeout(2000);
await page.screenshot({ path: 'test-results/pos-empty.png' });
await page.locator('section button:has-text("Haircut")').first().click();
await page.waitForTimeout(500);
const staffSelect = page.locator('aside select').first();
const options = await staffSelect.locator('option').allInnerTexts();
await staffSelect.selectOption({ index: 1 });
await page.screenshot({ path: 'test-results/pos-cart.png' });
await page.getByRole('button', { name: /Bill Payment/ }).click();
await page.waitForTimeout(800);
await page.screenshot({ path: 'test-results/pos-pay.png' });
await page.getByRole('button', { name: 'Exact' }).click();
await page.getByRole('button', { name: /^Pay Rs/ }).click();
await page.getByText('Bill completed').waitFor({ timeout: 30000 });
await page.screenshot({ path: 'test-results/pos-done.png' });
console.log('staff options', options.length, '| bill completed OK');
console.log('errors', errors);
await browser.close();
