GRANT USAGE ON SCHEMA public TO thehairc_haircut;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO thehairc_haircut;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO thehairc_haircut;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO thehairc_haircut;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO thehairc_haircut;